### ISSUE TITLE
The source code of InSilicoTEM v0.93

### ISSUE THREAD

**Issue by holyprince** [PhilippPelz/InSilicoTEM_mod#1]
Where can I find the source code of InSilicoTEM v0.93？I only can find the paper, and do not find the website of the software. Thank you !

**Comment by PhilippPelz** [comment]
I find it via Google. I can Google it for you if you can't find it.

Zihao Wang <notifications@github.com> schrieb am Fr., 25. Mai 2018, 03:42:

**Comment by holyprince** [comment]
@PhilippPelz  You are very warmhearted. If you are convient, can you give me the website which can download the raw InSilicoTEM v0.93? I want to find some helpful information from the website because of the lots of parameters.

**Comment by PhilippPelz** [comment]
Thanks!

Here is the download link: https://filemare.com/en/browse/qiftp.tudelft.nl/rieger/outgoing/InSilicoTEM, unfortunately, there is not much information on usage but you should be able to figure out most of it from the example files.

**Comment by nguyen14ck** [comment]
@PhilippPelz The file was moved. Could you upload it again? Thank you!
